services:
  - type: web
    name: mineguard-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false # You'll set this manually in Render dashboard
      - key: VITE_DEBUG
        value: "false"
